### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by schmelto** [Ritwik880/Ritwik880#2]
https://github.com/Ritwik880/Ritwik880/blob/master/README.md#L1

**Comment by Ritwik880** [comment]
Hey @schmelto can u be more specific.

**Comment by schmelto** [comment]
https://ritwik880.github.io/my-profile/
-> 404 not found

**Comment by Ritwik880** [comment]
@schmelto actually currently the Github pages are inactive, here I have hosted on heroku:
http://ritwik-sinha.herokuapp.com

**Comment by schmelto** [comment]
I would suggest using this link
